### PR TITLE
Apply senna to the website #16

### PR DESCRIPTION
**Pull request by mjbradford89**
Attached is an update for https://github.com/liferay/sennajs.com/issues/16.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @mjbradford89, could you make sure that Google Analytics events are being sent? This should be fine https://github.com/liferay/senna.js/blob/master/examples/ga/tracker.js

**Comment by mjbradford89** [comment]
Hey @zenorocha, sure.  I just pushed up 0f6e87d.  Let me know if that's good or if you think it should go in its' own `tracker.js` file.

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
