### PR TITLE
Configure CSP to avoid mixing content with relative urls

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://github.com/liferay/sennajs.com/issues/61

Unsure how we generate the static build for sennajs.com but this resolves the severe issue

### CODE REVIEW

**Comment by SpencerWoo** [comment]
Hi @diegonvs 
From the LRIS it sounds like you're handling the sennja.com site and I think this should be changed asap, lmk

I'll tag @julien and @jeffreydothan as they seem to be working on fixing this site in https://github.com/liferay/sennajs.com/tree/gh-pages

**Comment by diegonvs** [comment]
LGTM! I was going to suggest you to update in site templates but it's broken(#58).
We are planning to upgrade this website to use Gatsby in future.

**Comment by SpencerWoo** [comment]
ah okay. gatsby, awesome!

**Comment by diegonvs** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
